#pragma once
#include "CoreMinimal.h"

const TArray<FString> Words = 
{
    TEXT("cakes"),
    TEXT("water"),
    TEXT("plums"),
    TEXT("kings"),
    TEXT("Knife"),
    TEXT("abolishment"),
    TEXT("atmospheric"),
    TEXT("backgrounds"),
    TEXT("campgrounds"),
    TEXT("complainers"),
    TEXT("countryside"),
    TEXT("dangerously"),
    TEXT("disgraceful"),
    TEXT("disturbance"),
    TEXT("documentary"),
    TEXT("facetiously"),
    TEXT("fracedinous"),
    TEXT("filmography"),
    TEXT("fluoridates"),
    TEXT("lumberjacks"),
    TEXT("misanthropy"),
    TEXT("nefariously"),
    TEXT("palindromes"),
    TEXT("personality"),
    TEXT("playgrounds"),
    TEXT("playwrights"),
    TEXT("precautions"),
    TEXT("predictably"),
    TEXT("Republicans"),
    TEXT("semordnilap"),
    TEXT("speculation"),
    TEXT("stenography"),
    TEXT("subordinate"),
    TEXT("Switzerland"),
    TEXT("trampolines"),
    TEXT("undesirably"),
    TEXT("vouchsafing"),
    TEXT("workmanship") 
};